services:
  loki:
    image: grafana/loki:2.9.4
    ports:
      - "5002:5002"
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
      - loki-storage:/loki
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - loki-network
    restart: unless-stopped

  promtail:
    image: grafana/promtail:2.9.4
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki-network

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "5001:5001"  # Map host port 5001 to container port 3000
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_HTTP_PORT=5001  # Explicitly set Grafana's internal port
    depends_on:
      - loki
    networks:
      - loki-network
    restart: unless-stopped

volumes:
  loki-storage:
  grafana-storage:

networks:
  loki-network:
    driver: bridge
