auth_enabled: false

server:
  http_listen_port: 5002

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2025-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

limits_config:
  retention_period: 168h  # 7 days
  max_query_series: 500
  max_query_length: 721h

compactor:
  working_directory: /loki/compactor
  retention_enabled: true
  compaction_interval: 24h


