server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:5002/loki/api/v1/push

scrape_configs:
  - job_name: system #system logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/**/*.log
  
  - job_name: docker #docker logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: container_name
          __path__: /var/lib/docker/containers/*/*-json.log

